name: 05 - 1 - Event Filters and Activity Types.
on: 
    pull_request:
        types: [opened, synchronize]
        branches:
            main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Simple Step
              run: echo "Running Whenever a PR is opened or synchronized AND base branch is main"
              
