name: 11 - Working with Inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: Skip deployment and only print build output
                type: boolean
                default: false
            target:
                description: Which environemt the workflow will target
                type: environment
            tag:
                description: Release form which to build and deploy
                type: choice
                options: [v1,v2,v3]
                default: v3


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building forn tag ${{inputs.tag}}"
    deploy:
        needs: [ build ]
        if: ${{ needs.build.result == 'success' && inputs.dry-run == false }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploying to ${{inputs.target}}"
        


